version: "3.7"

services:
  app:
    image: github.com/dweidenfeld/shiftcal
    build:
      context: .
      target: dev
    ports:
      - 3000:3000
      - 10000:10000
    volumes:
      - .:/app:rw,cached
      - ./node_modules:/app/node_modules:rw,delegated
